[features]
seeds = false
skip-lint = false
[programs.localnet]
nested_account_resolution = "J5kQSQoRjuWYwPBKEWpMcttcZVU7f2WGLBQWFXNZCfVU"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/noahgundotra/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
